### ISSUE TITLE
Cannot build due to: `javafx.scene.layout.CornerRadiiConverter` is not a known java class

### ISSUE THREAD

**Issue by vsts** [Frege/FregeFX#2]
Hi,

when trying to build FregeFX from sources I get a compilation error:

```
E /tmp/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:4263: `javafx.scene.layout.CornerRadiiConverter` is not a known java class
fregefx.JavaFxAll: build failed because of compilation errors.
fregefx.JavaFxUtils: build failed because module `fregefx.JavaFxAll` not built.
```

My steps were cloning:

```
user@pc:/tmp$ git clone https://github.com/Frege/FregeFX.git
Cloning into 'FregeFX'...
remote: Counting objects: 206, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 206 (delta 0), reused 0 (delta 0), pack-reused 191
Receiving objects: 100% (206/206), 214.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (62/62), done.
Checking connectivity... done.
user@pc:/tmp$ cd FregeFX/
user@pc:/tmp/FregeFX$ ls
allJavaFX.groovy  build.gradle  examples  fregefx  fregefx.iml  gradle  gradle.properties  gradlew  gradlew.bat  LICENSE.txt  README.md  settings.gradle
```

Run `clean`:

```
user@pc:/tmp/FregeFX$ ./gradlew clean --stacktrace --info
Starting Build
Compiling settings file '/tmp/FregeFX/settings.gradle' using SubsetScriptTransformer.
Compiling settings file '/tmp/FregeFX/settings.gradle' using BuildScriptTransformer.
Settings evaluated using settings file '/tmp/FregeFX/settings.gradle'.
Projects loaded. Root project using build file '/tmp/FregeFX/build.gradle'.
Included projects: [root project 'fregefx', project ':examples', project ':fregefx']
Evaluating root project 'fregefx' using build file '/tmp/FregeFX/build.gradle'.
Compiling build file '/tmp/FregeFX/build.gradle' using SubsetScriptTransformer.
Compiling build file '/tmp/FregeFX/build.gradle' using BuildScriptTransformer.
Evaluating project ':examples' using build file '/tmp/FregeFX/examples/build.gradle'.
Compiling build file '/tmp/FregeFX/examples/build.gradle' using SubsetScriptTransformer.
Compiling build file '/tmp/FregeFX/examples/build.gradle' using BuildScriptTransformer.
Evaluating project ':fregefx' using build file '/tmp/FregeFX/fregefx/build.gradle'.
Compiling build file '/tmp/FregeFX/fregefx/build.gradle' using SubsetScriptTransformer.
Compiling build file '/tmp/FregeFX/fregefx/build.gradle' using BuildScriptTransformer.
using javafx from current java 8: /home/user/opt/jdk1.8.0_60/jre/lib/ext/
All projects evaluated.
Selected primary task 'clean' from project :
Tasks to be executed: [task ':examples:clean', task ':fregefx:clean']
:examples:clean (Thread[main,5,main]) started.
:examples:clean
Executing task ':examples:clean' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
:examples:clean UP-TO-DATE
:examples:clean (Thread[main,5,main]) completed. Took 0.012 secs.
:fregefx:clean (Thread[main,5,main]) started.
:fregefx:clean
Executing task ':fregefx:clean' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:fregefx:clean UP-TO-DATE
:fregefx:clean (Thread[main,5,main]) completed. Took 0.003 secs.

BUILD SUCCESSFUL

Total time: 17.036 secs
Stopped 0 compiler daemon(s).

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.6/userguide/gradle_daemon.html
```

Run `run`, which results in an error:

```
user@pc:/tmp/FregeFX$ ./gradlew run --stacktrace --info
Starting Build
Settings evaluated using settings file '/tmp/FregeFX/settings.gradle'.
Projects loaded. Root project using build file '/tmp/FregeFX/build.gradle'.
Included projects: [root project 'fregefx', project ':examples', project ':fregefx']
Evaluating root project 'fregefx' using build file '/tmp/FregeFX/build.gradle'.
Evaluating project ':examples' using build file '/tmp/FregeFX/examples/build.gradle'.
Evaluating project ':fregefx' using build file '/tmp/FregeFX/fregefx/build.gradle'.
using javafx from current java 8: /home/user/opt/jdk1.8.0_60/jre/lib/ext/
All projects evaluated.
Selected primary task 'run' from project :
Tasks to be executed: [task ':fregefx:compileJava', task ':fregefx:compileFrege', task ':fregefx:processResources', task ':fregefx:classes', task ':fregefx:jar', task ':examples:compileJava', task ':examples:compileFrege', task ':examples:processResources', task ':examples:classes', task ':examples:run']
:fregefx:compileJava (Thread[main,5,main]) started.
:fregefx:compileJava
Executing task ':fregefx:compileJava' (up-to-date check took 0.307 secs) due to:
  No history is available.
All input files are considered out-of-date for incremental task ':fregefx:compileJava'.
Compiling with JDK Java compiler API.
:fregefx:compileJava (Thread[main,5,main]) completed. Took 1.795 secs.
:fregefx:compileFrege (Thread[main,5,main]) started.
:fregefx:compileFrege
Executing task ':fregefx:compileFrege' (up-to-date check took 0.017 secs) due to:
  No history is available.
no module and no extra args given: compiling all of the sourceDir
Calling Frege compiler with args: '[-inline, -make, -sp, /tmp/FregeFX/fregefx/src/main/frege, -d, /tmp/FregeFX/fregefx/build/classes/main, /tmp/FregeFX/fregefx/src/main/frege]'
Starting process 'command '/home/user/opt/jdk1.8.0_60/bin/java''. Working directory: /tmp/FregeFX/fregefx Command: /home/user/opt/jdk1.8.0_60/bin/java -Xss4m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /home/user/.gradle/caches/modules-2/files-2.1/org.frege-lang/frege/3.22.524-gcc99d7e/68f62e4717540828a70fb10bcbe454909b11106/frege-3.22.524-gcc99d7e.jar frege.compiler.Main -inline -make -sp /tmp/FregeFX/fregefx/src/main/frege -d /tmp/FregeFX/fregefx/build/classes/main /tmp/FregeFX/fregefx/src/main/frege
Successfully started process 'command '/home/user/opt/jdk1.8.0_60/bin/java''
E /tmp/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:4263: `javafx.scene.layout.CornerRadiiConverter` is not a known java class
fregefx.JavaFxAll: build failed because of compilation errors.
fregefx.JavaFxUtils: build failed because module `fregefx.JavaFxAll` not built.
calling: javac -cp /home/user/.gradle/caches/modules-2/files-2.1/org.frege-lang/frege/3.22.524-gcc99d7e/68f62e4717540828a70fb10bcbe454909b11106/frege-3.22.524-gcc99d7e.jar:/tmp/FregeFX/fregefx/build/classes/main -d /tmp/FregeFX/fregefx/build/classes/main -sourcepath /tmp/FregeFX/fregefx/src/main/frege -encoding UTF-8 /tmp/FregeFX/fregefx/build/classes/main/fregefx/JavaFxProperties.java 
Note: /tmp/FregeFX/fregefx/build/classes/main/fregefx/JavaFxProperties.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /tmp/FregeFX/fregefx/build/classes/main/fregefx/JavaFxProperties.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Build failed.
runtime 35.441 wallclock seconds.
:fregefx:compileFrege FAILED
:fregefx:compileFrege (Thread[main,5,main]) completed. Took 36.118 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fregefx:compileFrege'.
> Process 'command '/home/user/opt/jdk1.8.0_60/bin/java'' finished with non-zero exit value 1

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':fregefx:compileFrege'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
    at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:158)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:36)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:103)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:102)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/home/user/opt/jdk1.8.0_60/bin/java'' finished with non-zero exit value 1
    at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:366)
    at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
    at org.gradle.process.internal.JavaExecAction$execute.call(Unknown Source)
    at frege.gradle.FregeTask.executeCompile(FregeTask.groovy:71)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 60 more


BUILD FAILED

Total time: 48.292 secs
Stopped 0 compiler daemon(s).
```

**Comment by Dierk** [comment]
Hi Volker, 

What JDK do you have?

If corner radius is not supported on your JDK, disable the respective style directive in the CSS file. 

Cheers
Dierk

sent from:mobile

**Comment by vsts** [comment]
It's Oracles JDK:

```
$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

How is compilation of [JavaFxAll.fr](https://github.com/Frege/FregeFX/blob/master/fregefx/src/main/frege/fregefx/JavaFxAll.fr#L4263) related to a CSS file?
I cannot find any CSS file in the FregeFX project, where should it be located? The only other file containing `CornerRadii` as string is [fregefx/types.properties](https://github.com/Frege/FregeFX/blob/master/fregefx/types.properties).

At least this is the only class not found: When I remove `CornerRadiiConverter` from `JavaFxAll.fr` it compiles.

Greetings
  Volker

**Comment by Dierk** [comment]
Ah, ok, I thought you were in the repl. 
Remove the native def in the JavaFxAll.fr. 

They said nothing had changed between u40 and u60 but that class did. 

Dierk

sent from:mobile

**Comment by vsts** [comment]
Maybe they accidentally removed it ;-)

Anyway, I keep it removed then. Thanks.

Regards
  Volker
